### ISSUE TITLE
Report dates stay the same when you change searches.

### ISSUE THREAD

**Issue by GKHWB** [Abidan-Archive/archive#52]
If you search from the archive home screen, the reports are labelled correctly with dates. If you search from the actual search page, they come up incorrectly.

Steps to reproduce:
1) On the archive homescreen, type in a search query and search for it. Results come up, and the dates are correctly labelled.
2) From the search screen, search for anything else. Different reports come up, but the dates remain identical to the first search.

Example in images:
![1](https://github.com/user-attachments/assets/3121ae4d-d548-49e3-951c-8027c0bde521)
![2](https://github.com/user-attachments/assets/a99cbe75-f825-4a68-bca9-90ad6e637ca1)
![3](https://github.com/user-attachments/assets/e2e2932f-2521-43ff-98a9-12707086dd51)

**Comment by manning390** [comment]
https://github.com/Abidan-Archive/archive/blob/978aa56b5002187dc2b7c9c5b713ab9570867c30/resources/js/Components/Report.svelte#L20C5-L20C77
